version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
   release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - moltin-import-{{ checksum "package.json" }}
      - run: yarn
      - run: npx semantic-release
workflows:
  version: 2
  full_release:
    jobs:
      - release:
          filters:
            branches:
              only: master
