version: 2
jobs:
  release:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - moltin-import-{{ checksum "package.json" }}
      - run: npx semantic-release