version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: moltin-import-{{ checksum "package.json" }}
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - moltin-import-{{ checksum "package.json" }}
      - run: yarn test
  release:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - moltin-import-{{ checksum "package.json" }}
      - run: npx semantic-release
workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - test